### ISSUE TITLE
@ignisda/nx-rust: nx dep-graph does not show dependencies between workspace crates

### ISSUE THREAD

**Issue by ndrsg** [IgnisDa/npm-libs#1]
Im using "@ignisda/nx-rust": "14.5.9", with "@nrwl/workspace": "14.5.10".

In my nx.json, i have:  "plugins": ["@ignisda/nx-rust"], set.

When running nx dep-graph there are no dependencies shown between my rust crates.

**Comment by IgnisDa** [comment]
Can you share your GitHub repository so that i can look into it?

If not possible, please show a screenshot of the graph.

**Comment by ndrsg** [comment]
https://github.com/ndrsg/nx-rust-demo

Thanks for having a look!

![image](https://user-images.githubusercontent.com/26137827/200808593-14b4fce3-1178-4e4d-989e-e5cd3531c806.png)


Expectation:
rust-app-one
              |---------> rust-lib-one ------> rust-lib-two
              |---------> rust-lib-two

**Comment by IgnisDa** [comment]
@ndrsg The name of the project in `workspace.json` should match the name in `Cargo.toml` of the projects. You have to make this change in `workspace.json`:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/60938164/200853989-84bd613d-6974-48e8-9fee-fbc00bf158bf.png">

Please feel free to reopen if you encounter another error!

**Comment by ndrsg** [comment]
thanks!
